spring.application.name=tree-app
server.port=8081

# ===============================
# SELECTORES DE ESTRATEGIA (WIRING)
# ===============================
# Parámetros globales para el intercambio dinámico de algoritmos y persistencias
app.tree-strategy=custom
app.storage=memory

# ===============================
# CONFIGURACIÓN POSTGRES 
# ===============================
# Cadena de conexión y credenciales para el motor de bases de datos relacionales
spring.datasource.url=jdbc:postgresql://localhost:5432/treedb
spring.datasource.username=postgres
spring.datasource.password=postgres

# ===============================
# CONFIGURACIÓN MONGODB 
# ===============================
# URI de conexión nativa para la persistencia NoSQL Documental local (Manejo Integrante C)
spring.data.mongodb.uri=mongodb://localhost:27017/tree_database