# Configuración de conexión para el Integrante C (MongoDB)
# Define la ruta del servidor local y la base de datos 'tree_db'
spring.data.mongodb.uri=mongodb://localhost:27017/tree_db

# Selector de estrategia: cambiar a 'mongo' para activar esta persistencia
app.storage=mongo