spring.datasource.url=jdbc:postgresql://postgres:5432/ecommerce
spring.datasource.username=admin
spring.datasource.password=admin123

spring.data.mongodb.host=mongo
spring.data.mongodb.port=27017
spring.data.mongodb.database=ecommerce