app.storage=memory
app.tree-strategy=custom

server.port=8080
spring.data.mongodb.uri=mongodb://localhost:27017/ecommerce

spring.datasource.url=jdbc:postgresql://localhost:5433/ecommerce
spring.datasource.username=admin
spring.datasource.password=admin123
